### ISSUE TITLE
Discrepancy in SVM-BPfinder Output: Input 440 sequences, output only 437 sequences

### ISSUE THREAD

**Issue by santataRU** [comprna/SVM-BPfinder-3M#1]
Dear Eduardo,

I input a FASTA file with 440 sequences, but the SVM-BPfinder output only contains results for 437 sequences. Could you help me understand the reason for this discrepancy?

Thank you for your assistance.

Best regards,

Xiao

link to access my input file: https://drive.google.com/file/d/1o_yOXhYZB5fHGDdXGhmDq0yuqlMuNDBz/view?usp=drive_link

**Comment by EduEyras** [comment]
Hi Xiao

SVMBPfinder will test all TNA positions for possible BPs at the A. Could it be that the sequences don't have TNAs?

If pass as input just a portion of the intron at the 3' end, It could be that BPs are further upstream. 

I hope this helps

Eduardo

**Comment by santataRU** [comment]
Hi Eduardo,

Thank you for your input. You’re right—these sequences don’t have TNAs. For instance, one sequence is:
"GAGGGTCTCGGGATCGAAAGTGCGCGGGGCTGCTTTCCGGGCGGGGAGAAGCTGGCGTGGGACTAGCTGGGGCCTGTGTCTCCTTGGCTCTCTATTTCAG".

I also noticed that the ppt_scr for some sequences is zero. Does this indicate the absence of a PPT in those introns with a zero score?

Best regards,
Xiao

**Comment by EduEyras** [comment]
Yes, the method will look for a ppt-looking region. It could find one even if it's short, but it could be zero if it's too short.

**Comment by santataRU** [comment]
> Yes, the method will look for a ppt-looking region. It could find one even if it's short, but it could be zero if it's too short.

Thank you very much for your input!
