### ISSUE TITLE
is it normal for a BP to get negative svm_scr score?

### ISSUE THREAD

**Issue by santataRU** [comprna/SVM-BPfinder-3M#2]
Dear Eduardo,

Is it normal for some BPs to have negative SVM scores (svm_scr score)? Do negative SVM scores indicate that these BPs are very weak and differ significantly from the BP consensus sequence?

I appreciate your insight.

Best regards,
Xiao

[table1_upregulated_100nt_3ss_unique_identifie_svm_score.xlsx](https://github.com/user-attachments/files/17384213/table1_upregulated_100nt_3ss_unique_identifie_svm_score.xlsx)

**Comment by EduEyras** [comment]
Hi Xiao,

yes, the score will distribution across negative and positive values, with higher positive scores meaning more confident BPs (overall). 

But the overall score is a combination of various elements. It could be that there is a very weak PPT (ppt_scr) or a divergent BP motif (bp_scr) or something similar that could penalise the final score. 

You can use the overall score as a ranking and select a single threshold, or select multiple thresholds using the ppt_scr and bp_scr.

I hope this helps

Best

Eduardo

**Comment by santataRU** [comment]
> Hi Xiao,
> 
> yes, the score will distribution across negative and positive values, with higher positive scores meaning more confident BPs (overall).
> 
> But the overall score is a combination of various elements. It could be that there is a very weak PPT (ppt_scr) or a divergent BP motif (bp_scr) or something similar that could penalise the final score.
> 
> You can use the overall score as a ranking and select a single threshold, or select multiple thresholds using the ppt_scr and bp_scr.
> 
> I hope this helps
> 
> Best
> 
> Eduardo

I see. Thank you very much for your input!
